# Material for MkDocs configuration file

# Project information
site_name: 'Status user docs specification'
site_url: https://help.status.im/
site_author: 'Status Research & Development GmbH'
site_description: 'Status app user documentation'

# Project directories
docs_dir: './docs/'
site_dir: './generated/'

# Repository
repo_name: 'Status user documentation and information architecture'
repo_url: https://github.com/status-im/help.status.im
edit_uri: edit/main/docs/

# Copyright
copyright: 'Status Research & Development GmbH'

# Theme configuration
theme:
    name: material
    custom_dir: './overrides/'
    logo: assets/images/status-logo-320x320.png
    favicon: assets/images/status-logo-32x32.png
    language: en
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: white
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: teal
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
    font:
      text: Inter
      code: Roboto Mono
    icon:
      repo: fontawesome/brands/github

      # Custom admonitions (callouts) require "Insiders" subscription
      admonition:
        # note: fontawesome/solid/note-sticky
        info: fontawesome/solid/circle-info
        tip: fontawesome/solid/wand-magic-sparkles
        # success: fontawesome/solid/circle-check
        # question: fontawesome/solid/question-circle
        warning: fontawesome/solid/triangle-exclamation
        # failure: fontawesome/solid/bomb
        # danger: fontawesome/solid/skull
        # bug: fontawesome/solid/robot

    # Material for MkDocs features
    features:
      - content.tooltips
      - search.suggest
      - search.highlight
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
    #  - navigation.indexes
      - navigation.top
      - navigation.tracking
      - content.action.edit
      - content.action.view
      - content.tabs.link

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list 
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - tables
  - toc:
      toc_depth: 2
      permalink: true
      title: Contents

# Theme customization
extra_css:
  - assets/stylesheets/extra.css

# Plugins
plugins:
  - search:
      lang: en
  - git-committers:
      docs_path: docs/
      repository: status-im/Status-User-Documentation-and-Information-Architecture
      branch: develop
  - git-revision-date
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

# Page tree (for the hamburger menu navigation)
nav:
  - Status user docs specification: index.md
  - Document example with all components: document-example-with-all-components.md
  - Document components description: document-components-desription.md