name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Clear Cache
        run: |
          rm -rf node_modules
          yarn cache clean
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: apt-get install pngquant 
      - run: pip install git+ssh://git@github.com/status-im/mkdocs-material-insiders.git
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: mkdocs gh-deploy --force
